_SMEKA_info = 1

# Make target to inform user about
# possible default env-vars that control the
# smeka installation procedure
.PHONY: smeka-info
smeka-info:
	@$(ECHO) "Default smeka command line variables:"
	@$(ECHO) ""
	@$(ECHO) "  OPT=none|debug|weak|medium|hard"
	@$(ECHO) "    define the optimization level of the compiler"
	@$(ECHO) ""
	@$(ECHO) "  VENDOR=gnu|intel"
	@$(ECHO) "    compiler vendor, defines the standard compiler variables"
	@$(ECHO) "    (comes in C/CXX/F_VENDOR variants to control them individually)"
	@$(ECHO) ""
	@$(ECHO) "  PIC=1|0"
	@$(ECHO) "    if 1 implicitly add the position independent code flag (from vendor)"
	@$(ECHO) ""
	@$(ECHO) "  SETUP=<file>"
	@$(ECHO) "    includes <file> in the Makefile project"
	@$(ECHO) "    this may hold any custom changes to the build system"
	@$(ECHO) ""
smeka: smeka-info

# Local Variables:
#  mode: makefile-gmake
# End:
